#!/usr/bin/env bash
#
# Prepare a stable nexenne release by updating the CMake version manifest and
# prepending an Org-mode changelog section generated from Conventional Commits.
# Supports both global snapshot releases and independent module releases.
set -euo pipefail

usage() {
    cat <<'USAGE'
usage: scripts/prepare_release.sh [--dry-run] [--kind snapshot|module] [--module NAME] [X.Y.Z]

Snapshot releases update NEXENNE_VERSION and use tags vX.Y.Z.
Module releases update NEXENNE_MODULE_<NAME>_VERSION and use tags
nexenne-<name>-vX.Y.Z.

Without X.Y.Z, git-cliff computes the next stable version. If no matching
stable tags exist yet, the current manifest version is used as the bootstrap
release. RC tags are intentionally ignored; pass only X.Y.Z here.
USAGE
}

dry_run=0
kind="snapshot"
module=""
target_version=""

while [ "$#" -gt 0 ]; do
    case "$1" in
        --dry-run)
            dry_run=1
            ;;
        --kind)
            shift
            if [ "$#" -eq 0 ]; then
                echo "prepare_release: --kind needs snapshot or module" >&2
                exit 2
            fi
            kind="$1"
            ;;
        --module)
            shift
            if [ "$#" -eq 0 ]; then
                echo "prepare_release: --module needs a module name" >&2
                exit 2
            fi
            module="$1"
            kind="module"
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        -*)
            echo "prepare_release: unknown option: $1" >&2
            usage >&2
            exit 2
            ;;
        *)
            if [ -n "$target_version" ]; then
                echo "prepare_release: only one version argument is allowed" >&2
                exit 2
            fi
            target_version="$1"
            ;;
    esac
    shift
done

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

version_file="cmake/nexenne_version.cmake"
changelog_file="CHANGELOG.org"

validate_stable_version() {
    case "$1" in
        *[!0-9.]*|*.*.*.*|.*|*.)
            return 1
            ;;
    esac
    printf '%s\n' "$1" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'
}

validate_module_name() {
    printf '%s\n' "$1" | grep -Eq '^[a-z][a-z0-9_]*$'
}

version_less_than() {
    [ "$(printf '%s\n%s\n' "$1" "$2" | sort -V | head -n 1)" = "$1" ] && [ "$1" != "$2" ]
}

module_var_name() {
    local name="$1"
    local upper
    upper="$(printf '%s\n' "$name" | tr '[:lower:]-' '[:upper:]_')"
    printf 'NEXENNE_MODULE_%s_VERSION\n' "$upper"
}

read_manifest_version() {
    local var_name="$1"
    sed -n "s/^set(${var_name}[[:space:]]*\"\\([^\"]*\\)\")$/\\1/p" "$version_file"
}

write_manifest_version() {
    local var_name="$1"
    local next="$2"
    local tmp
    tmp="$(mktemp)"
    sed "s/^set(${var_name}[[:space:]]*\".*\")$/set(${var_name} \"$next\")/" "$version_file" > "$tmp"
    mv "$tmp" "$version_file"
}

ensure_changelog() {
    local path="$1"
    if [ -f "$path" ]; then
        return
    fi
    cat > "$path" <<'EOF'
#+TITLE: Changelog
#+OPTIONS: toc:nil num:nil ^:nil
#+STARTUP: showall

All notable user-facing changes are generated from Conventional Commits.

# Generated by git-cliff. Do not edit release sections by hand.
EOF
}

if [ "$kind" != "snapshot" ] && [ "$kind" != "module" ]; then
    echo "prepare_release: --kind must be snapshot or module" >&2
    exit 2
fi
if [ "$kind" = "module" ]; then
    if [ -z "$module" ]; then
        echo "prepare_release: module releases require --module NAME" >&2
        exit 2
    fi
    if ! validate_module_name "$module" || [ ! -d "modules/$module" ]; then
        echo "prepare_release: unknown module: $module" >&2
        exit 2
    fi
fi

if ! command -v git-cliff >/dev/null 2>&1; then
    echo "prepare_release: git-cliff is required; install it before preparing a release" >&2
    exit 127
fi

if [ "$kind" = "snapshot" ]; then
    var_name="NEXENNE_VERSION"
    tag_prefix="v"
    tag_pattern='^v[0-9]+\.[0-9]+\.[0-9]+$'
    ignore_tags='^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$'
    cliff_args=(--tag-pattern "$tag_pattern" --ignore-tags "$ignore_tags")
else
    var_name="$(module_var_name "$module")"
    tag_prefix="nexenne-${module}-v"
    tag_pattern="^nexenne-${module}-v[0-9]+\\.[0-9]+\\.[0-9]+$"
    ignore_tags="^nexenne-${module}-v[0-9]+\\.[0-9]+\\.[0-9]+-rc\\.[0-9]+$"
    cliff_args=(
        --tag-pattern "$tag_pattern"
        --ignore-tags "$ignore_tags"
        --include-path "modules/$module/**"
        --include-path "doc/module/$module/**"
        --include-path "examples/$module/**"
    )
fi

current_version="$(read_manifest_version "$var_name")"
if ! validate_stable_version "$current_version"; then
    echo "prepare_release: invalid current $var_name: $current_version" >&2
    exit 1
fi

explicit_version=0
if [ -n "$target_version" ]; then
    explicit_version=1
else
    if git tag --list "${tag_prefix}*" | grep -Eq "$tag_pattern"; then
        target_version="$(git-cliff --config cliff.toml --bumped-version "${cliff_args[@]}")"
        target_version="${target_version#$tag_prefix}"
        target_version="${target_version#v}"
    else
        target_version="$current_version"
    fi
fi

if ! validate_stable_version "$target_version"; then
    echo "prepare_release: target version must be stable SemVer X.Y.Z: $target_version" >&2
    exit 1
fi

if version_less_than "$target_version" "$current_version"; then
    echo "prepare_release: target $target_version is older than current $current_version" >&2
    exit 1
fi

tag_name="${tag_prefix}${target_version}"
if git rev-parse -q --verify "refs/tags/$tag_name" >/dev/null; then
    if [ "$explicit_version" = "1" ]; then
        echo "prepare_release: $tag_name already exists" >&2
        exit 1
    fi
    echo "prepare_release: $tag_name already exists; no stable release needed"
    exit 0
fi

if [ "$dry_run" = "1" ]; then
    tmp_changelog="$(mktemp)"
    if [ -f "$changelog_file" ]; then
        cp "$changelog_file" "$tmp_changelog"
    else
        ensure_changelog "$tmp_changelog"
    fi
    git-cliff --config cliff.toml --unreleased --tag "$tag_name" \
        "${cliff_args[@]}" --strip header --prepend "$tmp_changelog" >/dev/null
    echo "prepare_release: would update $var_name to $target_version"
    echo "prepare_release: would prepare $tag_name"
    echo "prepare_release: changelog preview:"
    sed -n '1,120p' "$tmp_changelog"
    rm -f "$tmp_changelog"
    exit 0
fi

write_manifest_version "$var_name" "$target_version"
ensure_changelog "$changelog_file"
git-cliff --config cliff.toml --unreleased --tag "$tag_name" \
    "${cliff_args[@]}" --strip header --prepend "$changelog_file"

echo "prepare_release: updated $var_name to $target_version"
echo "prepare_release: prepared $tag_name"
